version: 2.1
jobs:
  build-and-test:
    parameters:
      ocaml-version: { type: string }
      base-version: { type: string }
    docker:
      - image: ocaml/opam:ubuntu-ocaml-<< parameters.ocaml-version >>
    environment:
      CI: true
      TC_NATIVE_OCAML_SWITCH: << parameters.ocaml-version >>
      TC_BASE_VERSION: << parameters.base-version >>
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v3-native-dependencies-<< parameters.ocaml-version >>-<< parameters.base-version >>-{{ .Branch }}-{{ checksum "tablecloth-native.opam" }}
            - v3-native-dependencies-<< parameters.ocaml-version >>-<< parameters.base-version >>-{{ .Branch }}-
            - v3-native-dependencies-<< parameters.ocaml-version >>-<< parameters.base-version >>-
      # m4 is a system dependency required by conf-m4 -> ocamlfind -> fmt -> alcotest
      - run: sudo apt-get install -y m4
      - run: make deps
      - run: make build
      - run: make test
      - run: make doc
      - run: make integration-test
      - save_cache:
          key: v3-native-dependencies-<< parameters.ocaml-version >>-<< parameters.base-version >>-{{ .Branch }}-{{ checksum "tablecloth-native.opam" }}
          paths:
            - ~/.opam

  source-code-formatting:
    docker:
      - image: ocaml/opam:ubuntu-ocaml-4.10
    environment:
      CI: true
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v0-source-dependencies-ocamlformat-0.19
      # m4 is a system dependency required by conf-m4 -> ocamlfind -> fmt -> alcotest
      - run: sudo apt-get install -y m4
      - run: echo 'export PATH=/usr/lib/cargo/bin/fd:$PATH' >> ~/.bash_env
      - run: make deps-format
      - run: make check-format
      - save_cache:
          key: v0-source-dependencies-ocamlformat-0.19
          paths:
            - ~/.opam

workflows:
  version: 2
  build:
    jobs:
      # --------------------
      # OCaml version matrix
      # --------------------
      # We currently only support native OCaml > 4.08, as we use the Fun module
      # which was only added in 4.08
      # Base 0.9.4 requires ocaml < 4.07, which we don't support
      # Base 0.10.0 requires ocaml < 4.07, which we don't support
      # Base 0.11.1 requires ocaml < 4.07, which we don't support
      # Base 0.12 requires ocaml < 4.10
      - build-and-test:
          matrix:
            parameters:
              base-version: ["v0.12.2"]
              ocaml-version: ["4.08", "4.09"]
      # Base 0.13.2 requires ocaml < 4.12
      - build-and-test:
          matrix:
            parameters:
              base-version: ["v0.13.2"]
              ocaml-version: ["4.08", "4.09", "4.10", "4.11"]
      # Base 0.14.1 requires ocaml >= 4.08
      # Currently broken as due to Either definition
      - build-and-test:
          matrix:
            parameters:
              base-version: ["v0.14.1"]
              ocaml-version: ["4.08", "4.09", "4.10", "4.11", "4.12"]
      - source-code-formatting
